# minimal test config

[service echo]
exec = /usr/bin/echo "Hello, World!"
restart = on-failure
provides = echo

[service echo2]
exec = /usr/bin/echo "Hello, World! 2"
restart = on-failure
provides = echo2
depends = echo